AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cpu-intensive

  Sample SAM Template for cpu-intensive

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  CPUIntensiveFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8


Outputs:
  CPUIntensiveFunction:
    Description: "CPU Intensice Lambda Function ARN"
    Value: !GetAtt CPUIntensiveFunction.Arn
  CPUIntensiveFunctionIamRole:
    Description: "Implicit IAM Role created for CPU Intensice function"
    Value: !GetAtt CPUIntensiveFunctionRole.Arn
